{
 "title": "Row A Rack 6 AC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "AC  Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.rack_inlet_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack Inlet Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.supply_air_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Supply Air Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.return_air_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Return Air Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Compresso Drive Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Power\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Compressor Voltages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "kvolt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Voltage\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Compressor Drive Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_current as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Current\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '6'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  }
 ]
}