{
 "title": "Row A Rack 8 Rack PDU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack PDU-A Power\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack PDU-B Power\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAnd R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Temp 1\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.temp2 as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Temp 2\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.humi as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Humidity\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC\n\n"
    }
   ]
  },
  {
   "title": "Line To Line Voltage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_ltol_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-A Input LtoL Voltage\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_ltol_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-B Input LtoL Voltage\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC\n"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_power_factor as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-A Power Factor\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_power_factor as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-B Power Factor\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nAND R.rack_number = '8'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  }
 ]
}