{
 "title": "Row A Reading Swarm",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Reading Swarm of Row A", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rack Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Temp 1\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.temp2 as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Temp 2\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Rack Humidty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.humi as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Humidity\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "AC Compressor Drive Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Voltage\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "AC Compressor Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Power\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "AC  Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.rack_inlet_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack Inlet Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.supply_air_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Supply Air Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.return_air_temp as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Return Air Temp\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "AC Compressor Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.compressor_drive_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Compresor Drive Current\") as metric\nFROM inlinerp RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "PDU Power",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack PDU-A Power\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_power as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" Rack PDU-B Power\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "PDU Line To Line Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_ltol_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-A Input LtoL Voltage\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_ltol_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-B Input LtoL Voltage\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "Row A Sum of UPS vs Sum of all Rack Power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  SUM(RE.pdub_power) + SUM(RE.pdua_power) as value,\n  CONCAT(\"Row A Rack Power\") as metric\nFROM rpdu RE\nWHERE $__timeFilter(RE.reading_dt)\nGROUP BY RE.reading_dt\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  SUM(RE.output_power_ltol_phase_1)+SUM(RE.output_power_ltol_phase_2) + SUM(RE.output_power_ltol_phase_3) as value,\n  CONCAT(\"Row A UPS Power\") as metric\nFROM ups2 RE\nWHERE $__timeFilter(reading_dt)\nGROUP BY RE.reading_dt\n"
    }
   ]
  },
  {
   "title": "PDU Power Factor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdua_power_factor as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-A Power Factor\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.pdub_power_factor as value,\n  CONCAT(R.row_id, \" \", R.rack_number, \" PDU-B Power Factor\") as metric\nFROM rpdu RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    }
   ]
  },
  {
   "title": "UPS1 Input Current",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_current_1_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Current Phase 1\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_current_1_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Current Phase 2\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_current_1_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Current Phase 3\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "UPS Output Current",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 1\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 2\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 3\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_ltol_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_ltol_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_current_ltol_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Current Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    }
   ]
  },
  {
   "title": "UPS2 Power Factor by Phase",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_factor_ltol_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Factor Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_factor_ltol_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Factor Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_factor_ltol_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Factor Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "UPS2 Output Power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_ltol_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_ltol_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_power_ltol_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Power Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "UPS1 Nominal Voltage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.nominal_voltage as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Nominal Voltage\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  },
  {
   "title": "UPS Output Voltage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage Phase 1\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage Phase 2\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage Phase 3\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_ltol_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoL Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_ltol_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoL Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_ltol_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoL Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_lton_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoN Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_lton_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoN Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.output_voltage_lton_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Output Voltage LtoN Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC\n"
    }
   ]
  },
  {
   "title": "UPS Input Voltage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_ltol_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage LtoL Phase 1\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_ltol_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage LtoL Phase 2\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_ltol_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage LtoL Phase 3\") as metric\nFROM ups2 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_1_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 1 Phase 1\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_1_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 1 Phase 2\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_1_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 1 Phase 3\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_2_phase_1 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 2 Phase 1\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_2_phase_2 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 2 Phase 2\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(RE.reading_dt) as time_sec,\n  RE.input_voltage_2_phase_3 as value,\n  CONCAT(R.row_id, \" \", R.rack_desc, \" Input Voltage 2 Phase 3\") as metric\nFROM ups1 RE\nJOIN rack R ON R.rack_id = RE.rack_id\nWHERE $__timeFilter(reading_dt)\nAND R.row_id = 'A'\nORDER BY RE.reading_dt, metric ASC"
    }
   ]
  }
 ]
}